language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible

script:
  - bundle exec kitchen test --concurrency=10 all

after_failure:
  - cat .kitchen/logs/*.log | grep -v '^I, '
