---
- name: install mysql
  sudo: yes
  apt: name=mysql-server

- name: install mysql-python for ansible
  sudo: yes
  apt: name=python-mysqldb

- name: check if database exists
  sudo: yes
  command: "mysql -e \"SHOW DATABASES LIKE '{{db_name}}';\""
  register: databases
  changed_when: False

- name: upload db dump
  copy: 'src={{db_dump}} dest={{remote_db_dump}}'
  when: "'{{db_name}}' not in databases.stdout"

- name: create database
  sudo: yes
  mysql_db: "name={{db_name}} state=present encoding=utf8"

- name: import database contents
  mysql_db: "name={{db_name}} state=import target={{remote_db_dump}}"
  when: "'{{db_name}}' not in databases.stdout"

- name: create db user
  sudo: yes
  mysql_user: "name={{db_user}} password={{db_password}} priv={{db_name}}.*:ALL state=present"
